DROP TABLE IF EXISTS tb_user;
CREATE TABLE tb_user(
	id INT NOT NULL AUTO_INCREMENT,
	uname VARCHAR(16) NOT NULL,
	age INT(3) NOT NULL,
	address VARCHAR(255) NOT NULL,	
	PRIMARY KEY(id)
)ENGINE = INNODB DEFAULT CHARSET=utf8;
 
INSERT INTO tb_user VALUES(NULL,'Zhang San',20,'上海'),(NULL,'Li Si',25,'北京'),(NULL,'Wang Wu',29,'杭州');